# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='bouncers',
            field=models.ManyToManyField(related_name='bouncer_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='invitees',
            field=models.ManyToManyField(related_name='invitee_parties', through='api.Invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
