# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180410_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('invitee', 'party')]),
        ),
    ]
