# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_party_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='facebook_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
