# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180411_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='location',
        ),
        migrations.AddField(
            model_name='party',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
