# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20180423_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='requesters',
            field=models.ManyToManyField(related_name='requester_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
